### ISSUE TITLE
Export fails if geometry is not defined

### ISSUE THREAD

**Issue by 0Nel** [dfki-ric/phobos#267] opened 2023-01-30 13:12 UTC
**Describe the bug**
During export I got an error in models.py at line 1353 saying: TypeError: 'tuple' object does not support item assignment. After further investigating on which link the error occured I figured that the reason for this issue was that the Geometry of that link was not defined.

**To Reproduce**
1. Create a model and don't define Geometry
2. Try to export model (smurf and urdf)
3. See TypeError

**Expected behavior**
No error, but maybe a user info on which link the geometry definition is missing

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04
 - Blender 3.4
 - python 3.8

**Comment by hwiedPro** [comment] 2023-01-31 13:08
Duplicate of https://github.com/dfki-ric/phobos/issues/265.
Already fixed but not yet released. ;)

**Closed by hwiedPro** 2023-01-31 13:08 UTC
